export enum homeConstants {
	SET_IS_LOGGED_IN = 'home/SET_IS_LOGGED_IN',
	FETCH_ALL_QUESTIONS = 'home/FETCH_ALL_QUESTIONS',
	SET_ALL_QUESTIONS = 'home/SET_ALL_QUESTIONS',

	OTHER_ACTION = 'home/OTHER_ACTION'
}
